title: Bisaya Poems
email: angbarug@mailfence.com 
description: >- # this means to ignore newlines until "baseurl:"
  For corrections and contributions, please consider submitting a push request or see our information on the 'About' page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bisaya_poems 
github_username: bisayapoems 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
