title: Learn Bisaya
email: angbarug@mailfence.com 
description: >- # this means to ignore newlines until "baseurl:"
  Angay ipa-sigarbo ang Binisayang pulong! Dasigon nato ang kabatan-onan sa pag kat-on sa linahum nga Binisaya.
  For corrections and contributions, please consider submitting a push request or see our information on the 'About' page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: learn_bisaya 
github_username: learnbisaya 

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
